### ISSUE TITLE
FileAlreadyExistsException after adding a KSP processor to a Gradle module with anvil-utils plugin enabled

### ISSUE THREAD

**Issue by arkivanov** [IlyaGulya/anvil-utils#4]
The anvil-utils plugin throws `FileAlreadyExistsException` when I add a KSP processor to a Gradle module with the plugin enabled.

```
> Task :<redacted>:kspDebugKotlin FAILED
e: [ksp] kotlin.io.FileAlreadyExistsException: /Users/arkivanov/workspace/<redacted>/build/generated/ksp/debug/kotlin/<redacted>/<redacted>Component_AssistedFactory.kt
        at com.google.devtools.ksp.common.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:154)
        at com.google.devtools.ksp.common.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:69)
        at com.google.devtools.ksp.processing.CodeGenerator.createNewFile$default(CodeGenerator.kt:59)
        at com.squareup.kotlinpoet.ksp.OriginatingKSFilesKt.writeTo(OriginatingKSFiles.kt:128)
        at me.gulya.anvil.utils.ksp.ContributesAssistedFactorySymbolProcessor.processChecked(ContributesAssistedFactorySymbolProcessor.kt:59)
        at me.gulya.anvil.utils.ksp.internal.ErrorLoggingSymbolProcessor.process(ErrorLoggingSymbolProcessor.kt:14)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:181)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
        at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)


```

**Comment by IlyaGulya** [comment]
@arkivanov could you please give me a bit more context?
Anvil version, KSP version, kotlin version, possibly example of a Component and its factory, how does your anvil configuration look like?

**Comment by arkivanov** [comment]
Sure!

Kotlin: 1.9.24
Dagger: 2.52
ksp: 1.9.24-1.0.20
dev.zacsweers.anvil: 0.4.0
anvil-utils: 0.3.0-beta01

After further investigation it appears that the error happens when the component depends on a class that's generated by another KSP processor.

```kotlin
@MyAnnotation // This annotation generates MyGeneratedClass under the same package
interface MyComponent {

    fun interface Factory {
        operator fun invoke(): MyComponent
    }
}

@ContributesAssistedFactory(UserScope::class, MyComponent.Factory::class)
class DefaultMyComponent @AssistedInject constructor(
    myGeneratedClass: MyGeneratedClass, // If I remove this dependency then the error disappears
) : MyComponent
```

I'm not sure, but it looks like anvil-utils is being executed second time (which may happen) and it tries to generate the same file second time.

**Comment by IlyaGulya** [comment]
Thanks!
I will take a look this weekend

**Comment by arkivanov** [comment]
Also this error happens if the component's class contains a dependency from an unresolved import.

```kotlin
import unresolved.package.name.MyClass

@ContributesAssistedFactory(UserScope::class, MyComponent.Factory::class)
class DefaultMyComponent @AssistedInject constructor(
    myClass: MyClass,
) : MyComponent
```

**Comment by IlyaGulya** [comment]
@arkivanov please test with this release and let me know if the issue is resolved
https://github.com/IlyaGulya/anvil-utils/releases/tag/v0.3.0-beta02

**Comment by arkivanov** [comment]
I tried the new version, it looks like the issue with [passing an unresolved dependency](https://github.com/IlyaGulya/anvil-utils/issues/4#issuecomment-2511308745) is now fixed, however the original issue still happens.

Here is the new stack trace:

```
[ksp] kotlin.io.FileAlreadyExistsException: /Users/arkivanov/workspace/<redacted>/build/generated/ksp/debug/kotlin/<redacted>/<redacted>Component_AssistedFactory.kt
	at com.google.devtools.ksp.common.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:154)
	at com.google.devtools.ksp.common.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:69)
	at com.google.devtools.ksp.processing.CodeGenerator.createNewFile$default(CodeGenerator.kt:59)
	at com.squareup.kotlinpoet.ksp.OriginatingKSFilesKt.writeTo(OriginatingKSFiles.kt:128)
	at me.gulya.anvil.utils.ksp.ContributesAssistedFactorySymbolProcessor.processChecked(ContributesAssistedFactorySymbolProcessor.kt:74)
	at me.gulya.anvil.utils.ksp.internal.ErrorLoggingSymbolProcessor.process(ErrorLoggingSymbolProcessor.kt:14)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:181)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by IlyaGulya** [comment]
@arkivanov thanks, I will take a look!

**Comment by IlyaGulya** [comment]
@arkivanov Unfortunately, I'm struggling to reproduce the issue 😅 
Could you please give me more insights on your project structure?
Specifically, which modules contain which code and which other KSP processors being run in each of them?
I've tried to reproduce the issue with following project structure and had no luck: 
https://github.com/IlyaGulya/anvil-utils/tree/reproducer/ksp-multi-round/compiler/src/test/fixtures/ksp-multi-round

I think I'm missing something 🙂

**Comment by arkivanov** [comment]
No problem. I migrated my [decompose-dagger-sample](https://github.com/arkivanov/decompose-dagger-sample) to Anvil and anvil-utils. And uploaded a reproducer for this issue to a separate [branch](https://github.com/arkivanov/decompose-dagger-sample/pull/new/anvil-utils-repro). Just run `./gradlew :feature-list:kspDebugKotlin`.

**Comment by IlyaGulya** [comment]
@arkivanov Thanks for the reproducer!
I've fixed this issue in this release: https://github.com/IlyaGulya/anvil-utils/releases/tag/v0.3.0-beta03
However, I've found another issue in the `Anvil` itself which causes your reproducer to fail: https://github.com/ZacSweers/anvil/issues/87
For now you can use Dagger KSP compiler instead of `generateDaggerFactories`, I suppose.

Let me know if there's something else left
